---
title: "yes_data_cleaning"
author: "Mallory Dobias"
date: "2024-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r}

if(!require(here)){install.packages('here')}
library(here)

if(!require(janitor)){install.packages('janitor')}
library(janitor)

if(!require(dplyr)){install.packages('dplyr')}
library(dplyr)

if(!require(stringr)){install.packages('stringr')}
library(stringr)

```

# Data Reading

```{r reading in data}

## Reading in NU English survey data

library(here) # places working directory at root of project folder

raw_data <- read.csv(here("data", "raw", "NU - YES - English - Questionnaires Optional_October 31, 2024_14.42.csv")) # directing to data from project folder root

head(raw_data)

```

# Data Cleaning

## Cleaning Var Names

```{r removing first two Qualtrics metadata rows}

## Removing first two rows with Qualtrics metadata

data_sliced <- raw_data %>%
  dplyr::slice(-1,-2)

# head(data_sliced) # looks good

## checking Qualtrics metadata rows are removed

search_for_string <- "Date" # creating string to search for

data_sliced %>%
  filter(stringr::str_detect(StartDate, search_for_string)) %>%
  nrow() == 0 # true if "Date" metadata rows are no longer in this column of data frame

```

```{r creating tidy names}

## Cleaning var names

data_named <- data_sliced %>%
  janitor::clean_names()

head(data_named)

## checking var names are now tidy

test_var_names <- tibble(col_names = names(data_named)) # creates data frame of names

test_var_names %>%
  filter(stringr::str_detect(col_names, "[A-Z]")) %>%
  nrow() == 0 # true if zero col names contain capital letters

```

```{r}

## Naming RISE vars

# first insert an underscore, then replace q with rise var name label

data_rise_named <- data_named %>%
  rename_with(~str_replace(., "^q([0-9]+)", "q_\\1"), starts_with("q")) %>%
  rename_with(~ str_replace(., "^q_", "proj_rise_q_"), starts_with("q_"))

## checking rise vars are named correctly

test_rise_pre <- data_named %>%
  select(starts_with("q"), -questionnaires, -contains("text")) %>%
  rename_with(~ str_extract(., "\\d+")) # extract digits from rise var names pre cleaning

test_rise_post <- data_rise_named %>%
  select(starts_with("proj_rise_"), -contains("commit"), -contains("text")) %>%
  rename_with(~ str_extract(., "\\d+")) # extract digits from rise var names post cleaning

identical(test_rise_pre, test_rise_post) # true if renamed columns (except text cols) are identical to original cols


```

