---
title: "yes_data_deidentified"
author: "Mallory Dobias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '5'
  word_document:
    toc: yes
    toc_depth: '5'
geometry: margin=0.50in
---

```{r setup, include=FALSE}

## Setting up R

knitr::opts_chunk$set(echo = TRUE)

if(!require(pointblank)){install.packages('pointblank')}
library(pointblank) # installing and calling pointblank package early in Markdown

validate_rmd(summary = TRUE, log_to_file = FALSE) # allowing validation from pointblank package within Markdown

```

```{r, include=FALSE}

if(!require(here)){install.packages('here')}
library(here)

if(!require(dplyr)){install.packages('dplyr')}
library(dplyr)

if(!require(stringr)){install.packages('stringr')}
library(stringr)

if(!require(tidyr)){install.packages('tidyr')}
library(tidyr)

if(!require(readr)){install.packages('readr')}
library(readr)

if(!require(purrr)){install.packages('purrr')}
library(purrr)

```

# Data Reading

```{r reading in data}

## Reading in all cleaned english survey data

library(here) # places working directory at root of project folder

turkish_data <- readRDS(here("data", "clean", "yes_data_turkish_clean.Rds")) # directing to data from project folder root

# test <- readRDS(here("data", "clean", "yes_data_turkish_clean_deidentified.Rds")) # directing to data from project folder root
# 
# glimpse(test)
# 
# test_2 <- read.csv(here("data", "clean", "yes_data_turkish_clean_deidentified.csv"))
# 
# glimpse(test_2)

```

# Selecting Data

```{r removing qual and text data}

## Removing text and qual vars

turkish_data_deidentified <- turkish_data %>%
  select(-contains("text"), -dem_hear_proj, -dem_why_interest, -dem_why_no_support, 
         -pfs_like, -pfs_change, -pfs_more_feedback, -advice,
         -(starts_with("abc_") & !contains("commit")), 
         -(starts_with("proj_care_") & !contains("commit")),
         -(starts_with("proj_pers_") & !contains("commit")),
         -contains("_tim_"))

# glimpse(turkish_data_deidentified)

```

# Checking Characters

```{r}

# Check column names for non-ASCII characters

colnames(turkish_data_deidentified) %>% 
  str_detect("\\P{ASCII}") %>%
  which(. == TRUE) # no col names with non-ascii chars

# Check values for non-ASCII characters

turkish_data_deidentified %>%
  mutate(across(everything(), ~str_detect(., "\\P{ASCII}"))) %>%  # Detect non-ASCII characters
  filter(rowSums(.) > 0) # no values with non-ascii chars

```

# Saving Data

```{r saving cleaned deidentified turkish data}

# Define the folder and file path

folder_path <- here("data", "clean")  # Path to my desired folder
file_name <- "yes_data_turkish_clean_deidentified.csv"
full_path <- file.path(folder_path, file_name)

# Save the dataframe to the .csv file

write.csv(turkish_data_deidentified, full_path, row.names = FALSE, quote = TRUE)

# Define the folder and file path

folder_path <- here("data", "clean")  # Path to my desired folder
file_name <- "yes_data_turkish_clean_deidentified.Rds"
full_path <- file.path(folder_path, file_name)

# Save the dataframe to the .rds file

saveRDS(turkish_data_deidentified, full_path)

```
