---
title: "yes_example_report"
author: "Mallory Dobias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '5'
  word_document:
    toc: yes
    toc_depth: '5'
geometry: margin=0.50in
---

```{r setup, include=FALSE}

## Setting up R

knitr::opts_chunk$set(echo = TRUE)

if(!require(pointblank)){install.packages('pointblank')}
library(pointblank) # installing and calling pointblank package early in Markdown

validate_rmd(summary = TRUE, log_to_file = FALSE) # allowing validation from pointblank package within Markdown

```

```{r, include=FALSE}

if(!require(here)){install.packages('here')}
library(here)

if(!require(dplyr)){install.packages('dplyr')}
library(dplyr)

if(!require(stringr)){install.packages('stringr')}
library(stringr)

if(!require(tidyr)){install.packages('tidyr')}
library(tidyr)

if(!require(readr)){install.packages('readr')}
library(readr)

if(!require(tidyverse)){install.packages('tidyverse')}
library(tidyverse)

if(!require(ggridges)){install.packages('ggridges')}
library(ggridges)

if(!require(showtext)){install.packages('showtext')}
library(showtext)

```

# Data Reading

```{r reading in data}

## Reading in cleaned survey data

library(here) # places working directory at root of project folder

data <- readRDS(here("data", "clean", "yes_data_nu_english_clean.Rds")) # directing to data from project folder root

# head(data) # looks good

```

# Outcomes 

## Hopelessness

Visualizing BHS scores pre vs. post ABC; 

```{r plot setup, include=FALSE, warning=FALSE}

## Loading required packages

library(tidyverse)
library(ggridges)
library(showtext)

## Setting up fonts

font_add_google(name = "Noto Sans",
                family = "noto sans")

showtext::showtext_auto()

```

```{r visualizing pre-post hopelessness abc setup, include=FALSE}

## Selecting pre and post vars for abc

pre_post_bhs_abc <- data %>% 
  filter(str_detect(ssi_started, "A.B.C.")) %>%
  dplyr::select(pre_bhs_mean, post_bhs_mean)

# Converting to long data format

pre_post_bhs_abc_long <- pivot_longer(pre_post_bhs_abc, 
                                           cols = contains("mean"), 
                                           names_to = "timing", 
                                           values_to = "hopelessness")

##  Renaming for plot

plot_data_bhs_abc <- pre_post_bhs_abc_long %>% 
  mutate(timing = case_when(str_detect(timing, "pre") ~ "Before",
         str_detect(timing, "post") ~ "After",
         is.na(timing) ~ NA_character_))

```

```{r writing plot function for future plots, include=FALSE}

## Writing a function for future plot setup

process_plot_data <- function(data, ssi_string, pre_var, post_var, outcome_label) {
  # Select pre and post variables based on the ssi string
  pre_post_outcome <- data %>%
    filter(str_detect(ssi_started, ssi_string)) %>%
    dplyr::select(contains(pre_var), 
                  contains(post_var))
  
  # Convert to long data format
  pre_post_outcome_long <- pre_post_outcome %>%
    pivot_longer(cols = contains("mean"), 
                 names_to = "timing", 
                 values_to = outcome_label)
  
  # Mutate 'timing' to label pre/post as 'Before'/'After'
  plot_data <- pre_post_outcome_long %>%
    mutate(timing = case_when(
      str_detect(timing, "pre") ~ "Before",
      str_detect(timing, "post") ~ "After",
      is.na(timing) ~ NA_character_
    ))
  
  return(plot_data)
}

```

```{r running custom plot function on abc data, include=FALSE}

## Running function on abc data

plot_data_bhs_abc_function <- process_plot_data(data, "A.B.C.", "pre_bhs_mean", "post_bhs_mean", "hopelessness")

```

```{r checking data frames are identical with and without function, include=FALSE}

identical(plot_data_bhs_abc, plot_data_bhs_abc_function) # true if processed data is identical using function

```

```{r visualizing pre-post hopelessness abc, include=FALSE, warning=FALSE}

## Plotting

plot_abc_bhs <- plot_data_bhs_abc_function %>%
  ggplot(aes(x = hopelessness, y = timing, fill = timing, color = timing)) +
  geom_density_ridges(alpha = 0.4,
                      jittered_points = TRUE,
                      position = "raincloud") +
  scale_fill_manual(values = c("blue", "grey")) +
  scale_color_manual(values = c("dark blue", "grey")) +
  scale_x_continuous(limits = c(0, NA)) +  # Set x-axis to start at 0, leave the upper limit as default
  theme_light() +
  theme(legend.position = "none",
        text = element_text(family = "noto sans"),
        title = element_text(size = 10),
        plot.background = element_rect(fill = "white")) +
  labs(x = "Hopelessness", y = " ",
       title = "Scores before and after ABC")

```

```{r plotting bhs pre and post abc, warning=FALSE}

plot_abc_bhs

```

