---
title: "YES Data Dictionaries"
author: "Mallory Dobias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '5'
  word_document:
    toc: yes
    toc_depth: '5'
geometry: margin=0.50in
---

```{r setup, include=FALSE}

## Setting up R

knitr::opts_chunk$set(echo = TRUE)

```

```{r packages, include=FALSE}

## Loading packages

if(!require(here)){install.packages('here')}
library(here)

if(!require(dplyr)){install.packages('dplyr')}
library(dplyr)

if(!require(stringr)){install.packages('stringr')}
library(stringr)

if(!require(tidyr)){install.packages('tidyr')}
library(tidyr)

if(!require(readr)){install.packages('readr')}
library(readr)

if(!require(tidyverse)){install.packages('tidyverse')}
library(tidyverse)

if(!require(rmarkdown)){install.packages('rmarkdown')}
library(rmarkdown)

if(!require(datadictionary)){install.packages('datadictionary')}
library(datadictionary)

```

```{r reading in data, include=FALSE}

## Reading in cleaned survey data

library(here) # places working directory at root of project folder

data <- readRDS(here("data", "clean", "yes_data_english_clean.Rds")) # directing to data from project folder root

```

# Data Dictionary

```{r creating data frame for dictionary, include=FALSE}

## Dropping qualtrics timing variables to make data dictionary more manageable

data_for_dictionary <- data %>%
  select(-contains("_tim_") & -contains("page_submit"))

```

```{r}

names(data_for_dictionary)

```

```{r creating var labels for dictionary, warning=FALSE}

# Create labels as a named vector. 
var_labels <- c(response_id = "id, qualtrics-generated",
                language = "response language",
                data_id = "id for dataset associated with each response (d01-d16)",
                start_date = "date response started",
                end_date = "date response closed",
                perc_progress = "percent survey complete, qualtrics-generated",
                finished = "true/false, is response 100% complete",
                ssi_source = "",
                ssi_choice = "ssi chosen",
                volunteer_questionnaires_yn = "yes/no, did they agree to optional questionnaires",
                reliant_mg = "yes/no, are they a patient in Reliant Medical Group in Massachusetts, d02 only",
                san_antonio = "yes/no, lives in San Antonio, d02 only",
                san_antonio_area = "where lives in San Antonio, d02 only",
                san_antonio_hear_proj = "chosen source for how they heard about yes, d02 only",
                dem_hear_proj = "qual, where did they hear about yes",
                dem_why_interest = "qual, why interested in yes",
                dem_receive_support = "have they received formal support before",
                dem_why_no_support = "qual, what prevented formal support",
                dem_location = "yes/no, do they live in a mixed city (Ramla, Lod, Jaffa, Haifa, Acre), d05 only",
                dem_adult = "yes/no, are they an adult (over 18), d02 only",
                dem_age = "age category",
                dem_sex = "sex assigned at birth",
                dem_gender_diff_sex = "yes/no, does gender differ from assigned sex",
                dem_gender_other_text = "qual, self-described gender identity",
                dem_gender_boy_man = "yes/no, identifies as a boy/man",
                dem_gender_girl_woman = "yes/no, identifies as a girl/woman",
                dem_gender_trans = "yes/no, identifies as trans",
                dem_gender_ftm_trans = "yes/no, identifies as ftm trans",
                dem_gender_mtf_trans = "yes/no, identifies as mtf trans",
                dem_gender_trans_masc = "yes/no, identifies as trans masculine",
                dem_gender_trans_fem = "yes/no, identifies as trans feminine",
                dem_gender_genderqueer = "yes/no, identifies as genderqueer",
                dem_gender_expansive = "yes/no, identifies as gender expansive",
                dem_gender_intersex = "yes/no, identifies as intersex",
                dem_gender_androgynous = "yes/no, identifies as androgynous",
                dem_gender_nonbinary = "yes/no, identifies as nonbinary",
                dem_gender_two_spirited = "yes/no, identifies as two-spirited",
                dem_gender_third_gender = "yes/no, identifies as third gender",
                dem_gender_agender = "yes/no, identifies as agender",
                dem_gender_unsure = "yes/no, unsure about gender identity",
                dem_gender_other = "yes/no, identifies as gender identity not listed above",
                dem_sex_orientation = "sexual orientation",
                dem_sex_orientation_other_text = "qual, self-described sexual orientation",
                dem_race_asian = "yes/no, identifies as Asian",
                dem_race_black = "yes/no, identifies as Black",
                dem_race_latin_hisp = "yes/no, identifies as Latine/Hispanic",
                dem_race_white = "yes/no, identifies as White",
                dem_race_other = "yes/no, identifies with a race/ethnicity not listed above",
                dem_ethnicity_text = "qual, self-described ethnicity, d05 only",
                dem_ethnicity_israeli = "yes/no, identifies as Israeli, d05 only",
                dem_ethnicity_african = "yes/no, identifies as African (Ethiopian), d05 only",
                dem_ethnicity_mid_eastern = "yes/no, identifies as Middle Eastern or Mediterranean, d05 only",
                dem_ethnicity_european_n_am = "yes/no, identifies as European or North American, d05 only",
                dem_ethnicity_s_central_am = "yes/no, identifies as South or Central American, d05 only",
                dem_ethnicity_ussr_e_european = "yes/no, identifies as from Former Soviet Union or Eastern Europe, d05 only",
                dem_ethnicity_ne_asian = "yes/no, identifies as Northeast Asian, d05 only",
                dem_ethnicity_other = "yes/no, identifies with an ethnicity not listed above, d05 only",
                ssi_prev_completed = "yes/no, previously completed an ssi",
                ssi_prev_completed_abc = "yes/no, previously completed abc",
                ssi_prev_completed_care = "yes/no, previously completed care",
                ssi_prev_completed_pp = "yes/no, previously completed project personality",
                ssi_prev_completed_rise = "yes/no, previously completed rise",
                ssi_times_completed_abc = "n times previously completed abc",
                ssi_times_completed_care = "n times previously completed care",
                ssi_times_completed_personality = "n times previously completed project personality",
                ssi_times_completed_rise = "n times previously completed rise",
                mfq_1 = "mfq item 1 score",
                mfq_2 = "mfq item 2 score",
                mfq_3 = "mfq item 3 score",
                mfq_4 = "mfq item 4 score",
                mfq_5 = "mfq item 5 score",
                mfq_6 = "mfq item 6 score",
                mfq_7 = "mfq item 7 score",
                mfq_8 = "mfq item 8 score",
                mfq_9 = "mfq item 9 score",
                mfq_10 = "mfq item 10 score",
                mfq_11 = "mfq item 11 score",
                mfq_12 = "mfq item 12 score",
                mfq_13 = "mfq item 13 score",
                mfq_total = "mfq composite score",
                pre_bhs_1 = "pre-ssi, beck hopelessness item 1",
                pre_bhs_2 = "pre-ssi, beck hopelessness item 2",
                pre_bhs_3 = "pre-ssi, beck hopelessness item 3",
                pre_bhs_4 = "pre-ssi, beck hopelessness item 4",
                pre_bhs_mean = "pre-ssi, beck hopelessness mean score",
                pre_shs_1 = "pre-ssi, state hope agency (pathways subscale) item 1",
                pre_shs_2 = "pre-ssi, state hope agency (pathways subscale) item 2",
                pre_shs_3 = "pre-ssi, state hope agency (pathways subscale) item 3",
                pre_shs_mean = "pre-ssi, state hope agency (pathways subscale) mean score",
                pre_self_hate_1 = "pre-ssi, self-hate item 1",
                pre_self_hate_2 = "pre-ssi, self-hate item 2",
                pre_self_hate_3 = "pre-ssi, self-hate item 3",
                pre_self_hate_mean = "pre-ssi, self-hate item 3",
                pre_perceived_control = "pre-ssi, perceived (lack of) control",
                ssi_started = "ssi started",
                abc_commit = "yes/no, commitment to finishing abc",
                abc_q_1_1_num = "mood rating",
                abc_q_2 = "youtube clip choice",
                abc_q_3_1_num = "mood rating",
                abc_q_4 = "youtube clip choice",
                abc_q_5 = "which positive emotions changed",
                abc_q_6_text = "qual, yt video, snapchat, tiktok that made them feel better",
                abc_q_7 = "chosen coping strategy",
                abc_q_8_text = "qual, one step toward coping strategy",
                abc_q_9 = "chosen way to connect socially",
                abc_q_9_15_text = "qual, self-described way to connect socially",
                abc_q_10 = "chosen larger goal",
                abc_q_11 = "smaller goal within larger goal",
                abc_q_11_7_text = "qual, self-described smaller goal within larger goal",
                abc_q_12 = "smaller goal within larger goal",
                abc_q_12_8_text = "qual, self-described smaller goal within larger goal",
                abc_q_13 = "smaller goal within larger goal",
                abc_q_13_7_text = "qual, self-described smaller goal within larger goal",
                abc_q_14 = "smaller goal within larger goal",
                abc_q_14_9_text = "qual, self-described smaller goal within larger goal",
                abc_q_15 = "smaller goal within larger goal",
                abc_q_15_6_text = "qual, self-described smaller goal within larger goal",
                abc_q_16 = "chosen activities to enjoy alone",
                abc_q_16_48_text = "qual, self-described activity to enjoy alone",
                abc_q_17_0_group = "day of week to do activity",
                abc_q_17_0_1_rank = "day of week to do activity",
                abc_q_17_0_2_rank = "day of week to do activity",
                abc_q_17_0_3_rank = "day of week to do activity",
                abc_q_17_0_4_rank = "day of week to do activity",
                abc_q_17_0_5_rank = "day of week to do activity",
                abc_q_17_0_6_rank = "day of week to do activity",
                abc_q_17_0_7_rank = "day of week to do activity",
                abc_q_18_0_group = "time of day to do activity",
                abc_q_18_0_1_rank = "time of day to do activity",
                abc_q_18_0_2_rank = "time of day to do activity",
                abc_q_18_0_3_rank = "time of day to do activity",
                abc_q_18_0_4_rank = "time of day to do activity",
                abc_q_18_0_5_rank = "time of day to do activity",
                abc_q_18_0_6_rank = "time of day to do activity",
                abc_q_19_0_group = "where to do activity",
                abc_q_19_0_1_rank = "where to do activity",
                abc_q_19_0_2_rank = "where to do activity",
                abc_q_19_0_3_rank = "where to do activity",
                abc_q_19_0_4_rank = "where to do activity",
                abc_q_19_0_5_rank = "where to do activity",
                abc_q_19_0_6_rank = "where to do activity",
                abc_q_19_0_7_rank = "where to do activity",
                abc_q_19_0_8_rank = "where to do activity",
                abc_q_19_8_text = "qual, where to do activity",
                abc_q_20_0_group = "how long to do activity",
                abc_q_20_0_1_rank = "how long to do activity",
                abc_q_20_0_2_rank = "how long to do activity",
                abc_q_20_0_3_rank = "how long to do activity",
                abc_q_20_0_4_rank = "how long to do activity",
                abc_q_20_0_5_rank = "how long to do activity",
                abc_q_21_0_group = "who to do activity with",
                abc_q_21_0_1_rank = "who to do activity with",
                abc_q_21_0_2_rank = "who to do activity with",
                abc_q_21_0_3_rank = "who to do activity with",
                abc_q_21_0_4_rank = "who to do activity with",
                abc_q_21_0_5_rank = "who to do activity with",
                abc_q_21_0_6_rank = "who to do activity with",
                abc_q_21_0_7_rank = "who to do activity with",
                abc_q_21_7_text = "qual, who to do activity with",
                abc_q_22 = "chosen roadblock",
                abc_q_23 = "biggest chosen roadblock",
                abc_q_24 = "chosen roadblock response",
                abc_q_24_7_text = "qual, person to ask for support",
                abc_q_24_8_text = "qual, way to practice self-compassion",
                abc_q_24_9_text = "qual, one small positive action",
                abc_q_37_text = "qual, what would they tell another teen",
                proj_care_commit = "yes/no, commitment to finishing care",
                proj_care_q_1_text = "qual, personal goal",
                proj_care_q_2_text = "qual, how person could practice self-kindness",
                proj_care_q_3 = "chosen roadblock",
                proj_care_q_4_text = "qual, way to overcome roadblock",
                proj_care_q_5_text = "qual, time when they were mean to themselves",
                proj_care_q_6_text = "qual, what would they tell another teen",
                proj_pers_commit = "yes/no, commitment to finishing project personality",
                proj_pers_q_1_text = "qual, how did person change",
                proj_pers_q_2_text = "qual, how would you feel if this happened",
                proj_pers_q_3_text = "qual, what would they tell another teen",
                proj_rise_commit = "yes/no, commitment to finishing project rise",
                proj_rise_q_4_text = "qual, most important identities",
                proj_rise_q_5 = "yes, do they need help answering",
                proj_rise_q_8 = "yes, do they still need help answering",
                proj_rise_q_13 = "yes, do they need help answering",
                proj_rise_q_17 = "yes/no, optional deep breathing exercise",
                proj_rise_q_25 = "yes/no, optional stories from others",
                proj_rise_q_28 = "chosen situations to relate to",
                proj_rise_q_29 = "chosen thoughts in response to oppression",
                proj_rise_q_29_5_text = "qual, self-described thoughts in response to oppression",
                proj_rise_q_31 = "chosen emotion in response to oppression",
                proj_rise_q_31_9_text = "qual, self-described emotion in response to oppression",
                proj_rise_q_32 = "yes/no, urge to self-harm",
                proj_rise_q_34 = "chosen action in response to oppression",
                proj_rise_q_34_7_text = "qual, self-described action in response to oppression",
                proj_rise_q_37 = "chosen action in response to oppression",
                proj_rise_q_37_7_text = "qual, self-described action in response to oppression",
                proj_rise_q_39 = "chosen story that resonates most",
                proj_rise_q_52 = "yes/no, read optional story",
                proj_rise_q_54 = "chosen coping statement",
                proj_rise_q_58_text = "qual, what would they tell another teen",
                proj_rise_q_59 = "chosen story to read",
                ssi_completed = "ssi completed",
                advice = "advice for others",
                advice_permission = "yes/no, permission to post anon advice",
                pfs_1 = "enjoyed activity",
                pfs_2 = "understood activity",
                pfs_3 = "activity was easy to use",
                pfs_4 = "tried their hardest during activity",
                pfs_5 = "activity helpful for others",
                pfs_6 = "recommend activity to a friend",
                pfs_7 = "agreed with activity",
                pfs_like = "qual, what they liked about activity",
                pfs_change = "qual, what they would change about activity",
                pfs_more_feedback = "qual, additional feedback",
                pfs_mean = "program feedback scale, mean score",
                perc_change_hope = "hopelessness compared to pre-ssi",
                perc_change_prob = "problem solving compared to pre-ssi",
                post_bhs_1 = "post-ssi, beck hopelessness item 1",
                post_bhs_2 = "post-ssi, beck hopelessness item 2",
                post_bhs_3 = "post-ssi, beck hopelessness item 3",
                post_bhs_4 = "post-ssi, beck hopelessness item 4",
                post_bhs_mean = "post-ssi, beck hopelessness mean score",
                post_shs_1 = "post-ssi, state hope agency (pathways subscale) item 1",
                post_shs_2 = "post-ssi, state hope agency (pathways subscale) item 2",
                post_shs_3 = "post-ssi, state hope agency (pathways subscale) item 3",
                post_shs_mean = "post-ssi, state hope agency (pathways subscale) mean score",
                post_self_hate_1 = "post-ssi, self-hate item 1",
                post_self_hate_2 = "post-ssi, self-hate item 2",
                post_self_hate_3 = "post-ssi, self-hate item 3",
                post_self_hate_mean = "post-ssi, self-hate item 3",
                post_perceived_control = "post-ssi, perceived (lack of) control")

```

```{r checking vector length}

# Printing list of vars to label

# var_labels_check <- tibble(item = colnames(data_for_dictionary))
# var_labels_check

# Checking if length of character vector is same as number of df columns

ncol(data_for_dictionary) == length(var_labels)

# Comparing the column names in the data frame with var_labels
colnames_data <- colnames(data_for_dictionary)

# Find missing and extra columns
missing_from_var_labels <- setdiff(colnames_data, names(var_labels))
extra_in_var_labels <- setdiff(names(var_labels), colnames_data)

# Print results
cat("Missing columns from var_labels:", missing_from_var_labels, "\n")
cat("Extra columns in var_labels:", extra_in_var_labels, "\n")

```

```{r creating data dictionary, warning=FALSE}

## Creating data dictionary

data_dictionary <- datadictionary::create_dictionary(data_for_dictionary, var_labels = var_labels)

## Defining the folder and file path

folder_path <- here("data", "clean")  # Path to my desired folder
file_name <- "yes_d09_data_dictionary.csv"
full_path <- file.path(folder_path, file_name)

write.csv(data_dictionary, full_path, row.names = FALSE)

```